### ISSUE TITLE
BUG: The App Crash When I access my user profile(related to the previous error) 

### ISSUE THREAD

**Issue by Kenan-Kamel** [Codepath-UIC-Team2/SportCave#33]
When I try to access the user profile, the app crash as a result of the favorite sports lists flagging errors with the following logs:

> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.sportcaveapp, PID: 11777
>     java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
>         at com.example.sportcaveapp.fragments.ProfileFragment.onViewCreated(ProfileFragment.java:99)
>         at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
>         at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
>         at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
>         at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
>         at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
>         at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
>         at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7356)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Kenan-Kamel** [comment]
Fixed: as a result of the previous bug.
